### ISSUE TITLE
Ran into this. Educated guess tells me this mod could be a culprit.

### ISSUE THREAD

**Issue by Sunconure11** [CammiePone/VehicleFix#1]
https://pastebin.com/VwC1xWJv

**Comment by CammiePone** [comment]
Wanna say how the bug was caused, or just gonna leave me guessing, 'cause I've stress tested it at this point on its own, and there haven't been any concurrent modification exceptions.

**Comment by Sunconure11** [comment]
It just... happened shortly after entering a world. No discernable cause.

**Comment by CammiePone** [comment]
Set up mixin output and send the class file so I can see how it looks.

**Comment by CammiePone** [comment]
Actually, I think it might be related to Pehkui because of this:
`at net.minecraft.entity.attribute.AttributeContainer.getCustomInstance(AttributeContainer:48)`

Specifically, I think Pehkui and my mod might be minorly incompatible but I'll have to check.

**Comment by Sunconure11** [comment]
[mixins.zip](https://github.com/CammiePone/VehicleFix/files/8098995/mixins.zip)

**Comment by CammiePone** [comment]
I only need class_1297, but ok gimme a moment

**Comment by CammiePone** [comment]
I think it's Salem, actually. Try removing it and see if you can get the crash to happen again.

**Comment by CammiePone** [comment]
Honestly, I should've realised it sooner that it wasn't me. I don't inject into `getBoundingBox(Entity)`. I inject into `adjustMovementForCollisions()`

**Comment by CammiePone** [comment]
Gonna make an update though to make it more obvious when my mod is the cause of a crash, at least when it comes to mixins.

**Comment by Sunconure11** [comment]
Crash happened again in the middle of adding stuff for use in bountiful. The crash is incredibly inconsistent.

**Comment by Sunconure11** [comment]
Of note is that the crash happened roughly sometime after spawning in some BW werewolves and BSM werepyres for testing

**Comment by Sunconure11** [comment]
https://pastebin.com/3MPgJd1K

Okay, so that's an entirely separate crash

**Comment by CammiePone** [comment]
It's also completely unrelated to my mods as that's looking at an empty itemstack with someone trying to get the use action. Also, I would suggested updating VehicleFix so the next time you get the original crash, we can verify beyond a shadow of a doubt that it isn't VehicleFix, since the method should now contain the mod name.
